### PR TITLE
tls-lwt: no double close

### PR DESCRIPTION
**Pull request by hannesm**
by first checking whether the fd has been closed already or not

### CODE REVIEW

**Comment by hcarty** [comment]
This seems like a much cleaner approach vs #395!

**Comment by cfcs** [comment]
Nice!

At the moment `mk_ch` (called by e.g. of_unix_file_descr`) assumes that he fd is open, so we can still end up in invalid states like this (unrelated to this PR):

```ocaml
# let fd = Unix.stderr in
Unix.close fd ;;
- : unit = ()
# Lwt_unix.state (Lwt_unix.of_unix_file_descr fd);;
- : Lwt_unix.state = Lwt_unix.Opened
```

**Comment by hcarty** [comment]
This does fix the original test I was using under #395 (`cohttp-curl-lwt https://www.google.com/ -v -o /dev/null`).

**Comment by hannesm** [comment]
@cfcs oh of course, the `Lwt_unix.state` is only lwt-internally tracked, i.e. if you use the `Unix` module for the underlying actual file descriptors, it won't work. This is something which may be worth discussing in the lwt issue tracker (whether there is a potential solution in lwt), but I don't think we will solve this in ocaml-tls.

**Comment by cfcs** [comment]
Woops, wrong repo :)

**Pull request merged**
