### PR TITLE
In Tls_lwt dont throw EPIPE error if we got close_notify

### LINKED ISSUE #347: handle shutdowns and last message sent by server gracefully
See https://github.com/mirage/ocaml-conduit/pull/116#issuecomment-266399924

If a `Tls_lwt` server sends a reply and then closes the connection (either directly, or via `Tls_lwt.Unix.close`) the client is sometimes not able to read the last message sent by the server.
This happens in https://github.com/mirage/ocaml-conduit/pull/116 when the system is under high CPU load, reading from the `Lwt_io` channel errors out with `"Tls_lwt.write" failed: Broken pipe`.

Making the server wait for the client to close the connection first works, but according to `SSL_shutdown(3)` this shouldn't be required:
"The shutdown procedure consists of 2 steps: the sending of the “close notify” shutdown alert and the reception of the peer's “close notify” shutdown  alert.  According to the TLS standard, it is acceptable for an application to only send its shutdown alert and then close the underlying connection without waiting for the peer's response"

Would it be possible for reading  on the Lwt_io channel to not return an error, at least when the server did send a close notify, but didn't wait for the client to send his?

### PR DESCRIPTION
**Pull request by rymdhund**
I don't really have any understanding of this lib, but i think this would fix #347.

### CODE REVIEW

**Comment by hannesm** [comment]
this seems to me to handle more `EPIPE` than intended originally.

Isn't a viable solution to add `Sys.(set_signal sigpipe Signal_ignore)` to your application (/cc @edwintorok)?  That's at least what I learned to do in various OCaml applications (even when not using this TLS library).

**Comment by edwintorok** [comment]
The test code already sets sigpipe to ignore https://github.com/mirage/ocaml-conduit/blob/b74dbbda7cbcce1b3d398d7499efd99eec7c62b4/tests/unix/cdtest_tls.ml#L62, however that only means that instead of raising a signal you get `EPIPE` from the system call, which caused the tls code to raise an exception.

The original problem in the referenced bug was that when that exception is raised we actually loose the last message sent by the other side; I haven't checked exactly what happens but my guess is you get a short read and then if the code insists reading again it gets an EPIPE. We should first return whatever the last message was, process it through the TLS state machine,  and raise the exception only if we get EPIPE and we haven't reached EOF yet.
In that sense the code in this PR seems to do the right thing, but I haven't tested it yet.

**Comment by hannesm** [comment]
@edwintorok thanks for explanation.  from what I read [in the spec](http://pubs.opengroup.org/onlinepubs/009695399/functions/read.html), `read` should never return `EPIPE` -- it is `write` which may return `EPIPE`.

if you find the time to test this PR, I'd be very interested whether it fixes the issue for you.  please report back.

**Comment by anmonteiro** [comment]
I'm also seeing reproducible `EPIPE` signals that cause the last chunk of data from the remote endpoint to be lost. I tried this PR, however, without success.

**Comment by anmonteiro** [comment]
I just opened #387 with an alternative to this PR that I think is less invasive and actually fixes the symptom in my application.

**Comment by hannesm** [comment]
thanks, tls 0.9.3 is released (PRed to opam-repository https://github.com/ocaml/opam-repository/pull/13231) which fixes this issue

**Pull request closed without merging**
