### PR TITLE
Mirage 2.3.0

### PR DESCRIPTION
**Pull request by hannesm**
this includes/supersedes #225 -- and reports a proper error to the user

### CODE REVIEW

**Comment by hannesm** [comment]
this will fail unless https://github.com/ocaml/opam-repository/pull/3694 is merged..

**Comment by avsm** [comment]
mirage-types-lwt is now merged

**Comment by pqwy** [comment]
This is obviously correct by cursory inspection of the change.

Also, more than half the affected lines compile on my current setup.

What go even go wrong?

**Comment by samoht** [comment]
Any plan to release of new version of ocaml-tls with this patch?

**Comment by hannesm** [comment]
yes, my plan is to wait for https://github.com/mirleft/ocaml-x509/pull/44 and #259 getting merged; and then release..

**Pull request merged**
