### PR TITLE
another topkg attempt

### PR DESCRIPTION
**Pull request by hannesm**
instead of in #337, I focus only on the topkg bits, not any interface design

### CODE REVIEW

**Comment by hannesm** [comment]
managed to solve (hopefully) myself by adding a `api:[]` into `pkg.ml` (and using path 2 above).

**Comment by hannesm** [comment]
(update: no, can't get it working)

**Comment by hannesm** [comment]
update: works now, pls look whether you're happy with this and if so, merge. thx.

**Comment by pqwy** [comment]
Could you just pls squash a stylesheet removal into that? `topkg` will use `odig`'s stylesheet, so no need for every repo to have its own snapshot of it.

Blue links. **shudder**

**Comment by hannesm** [comment]
done

**Pull request merged**
