### PR TITLE
Async

### PR DESCRIPTION
**Pull request by vbmithr**
Do not merge yet, WIP.

I'm trying to add an Async backend to `ocaml-tls`!

### CODE REVIEW

**Comment by rgrinberg** [comment]
Anything I can do to help this along?

**Comment by vbmithr** [comment]
Read and look for obvious issues. It does not work currently, not sure
why. Try to make examples work. Thanks!

**Comment by rgrinberg** [comment]
The rename from core to types needs a little more thinking. `Tls.Core` is currently part of the public interface and  `Tls.Types` isn't a very good substitute.

**Comment by hannesm** [comment]
thanks for this PR, this has been subsequently re-developed, and finally (with tls 0.13.2) async support is available as `opam install tls-async` (see #432 for the PR that got merged and released).

**Pull request closed without merging**
