### PR TITLE
mirage: update the the new error scheme

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
@pqwy @hannesm `master` seems completely broken?

```
#=== ERROR while installing x509.0.5.3 ========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml pkg/pkg.ml build --pinned true
# path         /home/travis/.opam/4.03.0/build/x509.0.5.3
# compiler     4.03.0
# exit-code    1
# env-file     /home/travis/.opam/4.03.0/build/x509.0.5.3/x509-17518-374d58.env
# stdout-file  /home/travis/.opam/4.03.0/build/x509.0.5.3/x509-17518-374d58.out
# stderr-file  /home/travis/.opam/4.03.0/build/x509.0.5.3/x509-17518-374d58.err
### stdout ###
# ocamlfind ocamldep -package 'asn1-combinators cstruct nocrypto sexplib astring' -modules lib/x509.ml > lib/x509.ml.depends
# ocamlfind ocamldep -package 'asn1-combinators cstruct nocrypto sexplib astring' -modules lib/x509.mli > lib/x509.mli.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -principal -package 'asn1-combinators cstruct nocrypto sexplib astring' -w +A-4-41-42-44 -I lib -o lib/x509.cmi lib/x509.mli
# + ocamlfind ocamlc -c -g -bin-annot -safe-string -principal -package 'asn1-combinators cstruct nocrypto sexplib astring' -w +A-4-41-42-44 -I lib -o lib/x509.cmi lib/x509.mli
# File "lib/x509.mli", line 161, characters 20-30:
# Error: Unbound module Asn.Time
```

**Comment by hannesm** [comment]
master is not up-to-date with asn1 and x509 master (you need #343)... I agree this is not in a good state atm... but mirage-dev uses tls master (and asn1/x509 releases from opam repository)...

this PR still has a bit too many error lifts, I'd hope we can get rid of more... will try to find some time soon to look into this (thx for the PR!)

**Comment by samoht** [comment]
@hannesm some number of lift as before :p just check the whole diff (that I tried to minimise), not the last commit.

**Comment by hannesm** [comment]
thanks, merged via #350

**Pull request closed without merging**
