### PR TITLE
API fixes for nocrypto master

### PR DESCRIPTION
**Pull request by pqwy**

### CODE REVIEW

**Comment by hannesm** [comment]
this breaks CBC with TLS-1.0...

**Comment by hannesm** [comment]
(running `test_server.native 4433` against `openssl s_client -tls1`)

**Comment by pqwy** [comment]
Oh, yeah, sorry. Was computing the carry-over IV from decrypted plaintext.

**Comment by hannesm** [comment]
thx, awesome!

**Pull request merged**
